-- Insert para fila 1
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Allen "Dr. Ernesto Accame"', 
    'TAURO_53@YAHOO.COM.AR', 
    'MORDIL@SPEEDY.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'DR Hugo Niz (Medico Pediatra)', 
    'Bioq Alejandro Moretti', 
    NULL, 
    NULL, 
    NULL, 
    2941452530, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'Ing. Quesnel s/n', 
    'Allen', 
    'Río Negro', 
    2941452530, 
    'Lic. Patricia Osses', 
    'Hospital'
);

-- Insert para fila 2
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Zonal Bariloche "Ramon Carrillo"', 
    'NEO@HOSPITALBARILOCHE.COM.AR', 
    'HOSPITAL@BARILOCHE.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dra. Fabiana Herbon', 
    'Dra. Adriana Ranieri', 
    NULL, 
    NULL, 
    NULL, 
    2944426117, 
    29442426100, 
    NULL, 
    NULL, 
    NULL, 
    'Moreno 601', 
    'San Carlos de Bariloche', 
    'Río Negro', 
    2944426117, 
    'Dra. Graciela Tapia Massini', 
    'Hospital'
);

-- Insert para fila 3
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Clínica Beccar', 
    'CLINICABECCAR@YAHOO.COM.AR', 
    'PLANOFABIAN@YAHOO.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Plano', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    47476381, 
    47430396, 
    47422509, 
    NULL, 
    NULL, 
    'Julian Navarro 48', 
    'Beccar', 
    'Buenos Aires', 
    47476381, 
    'Enfermera Soledad Lugo', 
    'Hospital'
);

-- Insert para fila 4
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Provincial Neuquén', 
    'HOSPITALPNNQN@YAHOO.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Mario Alcorta', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    2994454610, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'Buenos Aires 700', 
    'Neuquén', 
    'Neuquén', 
    2994454610, 
    'Bioq. Liliana Guerrero', 
    'Hospital'
);

-- Insert para fila 5
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Clínica Modelo S.A', 
    'INFO@CLINICAMODELO.COM.AR', 
    'ADMISION@CLINICAMODELO.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Cimadevilla, Jorge D', 
    'Dr. Pucheu, Hugo L', 
    NULL, 
    NULL, 
    NULL, 
    2494387500, 
    2494387587, 
    NULL, 
    NULL, 
    NULL, 
    'Vélez Sarsfield 55', 
    'Luján', 
    'Buenos Aires', 
    2494387500, 
    'Ing. Juan Domínguez', 
    'Hospital'
);

-- Insert para fila 6
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio San Carlos', 
    'SANATORIOSANCARLOS@HOTMAIL.COM.AR', 
    'SANATORIOSANCARLOS@HOTMAIL.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Pedro Rodriguez', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    2926442601, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'Belgrano 525', 
    'San Carlos de Bariloche', 
    'Río Negro', 
    2926442601, 
    'Dr. Pedro Rodriguez', 
    'Hospital'
);

-- Insert para fila 7
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Zonal Esquel', 
    'DIRECCION@HOSPITALESQUEL.COM.AR', 
    'SAMIC@HOSPITALESQUEL.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dra. Viviana Bettini', 
    'Dra. Claudia Linares', 
    NULL, 
    NULL, 
    NULL, 
    2945453033, 
    2945453021, 
    NULL, 
    NULL, 
    NULL, 
    'Calle Primo Capraro', 
    'Esquel', 
    'Chubut', 
    2945453033, 
    'Dr. Miguel Huenupan', 
    'Hospital'
);

-- Insert para fila 8
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2,
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITALZONAL@MADRYN.ORG.AR', 
    'NEUROZONAMADRYN@YAHOO.COM.AR', 
    'CGONZALEZ@MADRYN.ORG.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Pedro Carranza', 
    'Lic. Mónica Nuñez', 
    NULL, 
    NULL, 
    NULL, 
    2804479301, 
    2804479301, 
    NULL, 
    NULL, 
    NULL, 
    'Avenida Gales 1466', 
    'Puerto Madryn', 
    'Chubut', 
    2804479301, 
    'Dr. Pedro Carranza', 
    'Hospital'
);

-- Insert para fila 9
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio del Sol', 
    'INFO@SANATORIODELSOL.COM.AR', 
    'SANATORIODELSOL@YAHOO.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Gustavo Piscicelli', 
    'Dr. Alejandro Pardo', 
    NULL, 
    NULL, 
    NULL, 
    2615068111, 
    2614311111, 
    NULL, 
    NULL, 
    NULL, 
    'Chacras de Coria', 
    'Luján de Cuyo', 
    'Mendoza', 
    2615068111, 
    'Dr. Gustavo Piscicelli', 
    'Hospital'
);

-- Insert para fila 10
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Británico', 
    'INFO@HOSPITALBRITANICO.ORG.AR', 
    'DIRECCIONDEMAIL1@HOSPITALBRITANICO.ORG.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Federico Pérez', 
    'Dr. Marcos Villar', 
    NULL, 
    NULL, 
    NULL, 
    1148117000, 
    1148117222, 
    NULL, 
    NULL, 
    NULL, 
    'Perdriel 74', 
    'Buenos Aires', 
    'Buenos Aires', 
    1148117000, 
    'Lic. María Soler', 
    'Hospital'
);
-- Insert para fila 11
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Italiano', 
    'INFO@HOSPITALITALIANO.ORG.AR', 
    'CONTACTO@HOSPITALITALIANO.ORG.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Ricardo Peralta', 
    'Dr. Lucas Martínez', 
    NULL, 
    NULL, 
    NULL, 
    1154635000, 
    1154635000, 
    NULL, 
    NULL, 
    NULL, 
    'Gascón 450', 
    'Buenos Aires', 
    'Buenos Aires', 
    1154635000, 
    'Lic. Laura Fernández', 
    'Hospital'
);

-- Insert para fila 12
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio Güemes', 
    'INFO@SANATORIOGUEMES.COM.AR', 
    'CONTACTO@SANATORIOGUEMES.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Carlos Martínez', 
    'Dr. Pablo Gómez', 
    NULL, 
    NULL, 
    NULL, 
    3814505000, 
    3814505123, 
    NULL, 
    NULL, 
    NULL, 
    'Av. Entre Ríos 450', 
    'San Miguel de Tucumán', 
    'Tucumán', 
    3814505000, 
    'Dr. Carlos Martínez', 
    'Hospital'
);

-- Insert para fila 13
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio Allende', 
    'CONTACTO@SANATORIOALLENDE.COM.AR', 
    'INFO@SANATORIOALLENDE.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Martín Soto', 
    'Dr. Laura Romero', 
    NULL, 
    NULL, 
    NULL, 
    3514689400, 
    3514689401, 
    NULL, 
    NULL, 
    NULL, 
    'Mariano Larra 345', 
    'Córdoba', 
    'Córdoba', 
    3514689400, 
    'Dr. Martín Soto', 
    'Hospital'
);

-- Insert para fila 14
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Clínica del Sol', 
    'INFO@CLINICADELSOL.COM.AR', 
    'CLINICADELSOL@YAHOO.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Eduardo García', 
    'Dr. Marcos Sánchez', 
    NULL, 
    NULL, 
    NULL, 
    2615008000, 
    2615008111, 
    NULL, 
    NULL, 
    NULL, 
    'Av. Colón 827', 
    'Mendoza', 
    'Mendoza', 
    2615008000, 
    'Dr. Eduardo García', 
    'Hospital'
);

-- Insert para fila 15
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Privado de Córdoba', 
    'INFO@HOSPITALPRIVADO.COM.AR', 
    'INFO@HOSPITALPRIVADO.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Marcelo Quirós', 
    'Dr. José Gómez', 
    NULL, 
    NULL, 
    NULL, 
    3514688200, 
    3514688201, 
    NULL, 
    NULL, 
    NULL, 
    'Avenida Naciones Unidas 346', 
    'Córdoba', 
    'Córdoba', 
    3514688200, 
    'Dr. Marcelo Quirós', 
    'Hospital'
);

-- Insert para fila 16
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio de la Trinidad', 
    'INFO@SANATORIOTRINIDAD.COM.AR', 
    'CONTACTO@SANATORIOTRINIDAD.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Andrés López', 
    'Dr. Santiago Pérez', 
    NULL, 
    NULL, 
    NULL, 
    1158002500, 
    1158002600, 
    NULL, 
    NULL, 
    NULL, 
    'Mitre 2020', 
    'Buenos Aires', 
    'Buenos Aires', 
    1158002500, 
    'Dr. Andrés López', 
    'Hospital'
);

-- Insert para fila 17
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Alemán', 
    'INFO@HOSPITALALEMAN.COM.AR', 
    'CONTACTO@HOSPITALALEMAN.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Santiago Olivera', 
    'Dr. Martín González', 
    NULL, 
    NULL, 
    NULL, 
    1143758200, 
    1143758201, 
    NULL, 
    NULL, 
    NULL, 
    'Av. Pueyrredón 1640', 
    'Buenos Aires', 
    'Buenos Aires', 
    1143758200, 
    'Dr. Santiago Olivera', 
    'Hospital'
);

-- Insert para fila 18
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Español', 
    'INFO@HOSPITALESPAÑOL.COM.AR', 
    'CONTACTO@HOSPITALESPAÑOL.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Enrique Sánchez', 
    'Dr. Pablo Ramírez', 
    NULL, 
    NULL, 
    NULL, 
    1154509500, 
    1154509501, 
    NULL, 
    NULL, 
    NULL, 
    'Av. Belgrano 2710', 
    'Buenos Aires', 
    'Buenos Aires', 
    1154509500, 
    'Dr. Enrique Sánchez', 
    'Hospital'
);

-- Insert para fila 19
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Italiano de Rosario', 
    'INFO@HOSPITALITALIANOROSARIO.ORG.AR', 
    'CONTACTO@HOSPITALITALIANOROSARIO.ORG.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Alberto López', 
    'Dr. María González', 
    NULL, 
    NULL, 
    NULL, 
    3414994400, 
    3414994401, 
    NULL, 
    NULL, 
    NULL, 
    'Bv. Oroño 450', 
    'Rosario', 
    'Santa Fe', 
    3414994400, 
    'Dr. Alberto López', 
    'Hospital'
);

-- Insert para fila 20
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio Güemes', 
    'INFO@SANATORIOGUEMES.COM.AR', 
    'CONTACTO@SANATORIOGUEMES.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Carlos Martínez', 
    'Dr. Pablo Gómez', 
    NULL, 
    NULL, 
    NULL, 
    3814505000, 
    3814505123, 
    NULL, 
    NULL, 
    NULL, 
    'Av. Entre Ríos 450', 
    'San Miguel de Tucumán', 
    'Tucumán', 
    3814505000, 
    'Dr. Carlos Martínez', 
    'Hospital'
);

-- Insert para fila 21
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Universitario Austral', 
    'INFO@HUA.ORG.AR', 
    'CONTACTO@HUA.ORG.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Juan López', 
    'Dr. María García', 
    NULL, 
    NULL, 
    NULL, 
    2304488000, 
    2304488111, 
    NULL, 
    NULL, 
    NULL, 
    'Av. Perón 1500', 
    'Pilar', 
    'Buenos Aires', 
    2304488000, 
    'Dr. Juan López', 
    'Hospital'
);

-- Insert para fila 22
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital El Cruce', 
    'INFO@HOSPITALELCRUCE.ORG.AR', 
    'CONTACTO@HOSPITALELCRUCE.ORG.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Martín Sánchez', 
    'Dr. Laura Pérez', 
    NULL, 
    NULL, 
    NULL, 
    1168178000, 
    1168178111, 
    NULL, 
    NULL, 
    NULL, 
    'Camino de Cintura y Mariano Acosta', 
    'Florencio Varela', 
    'Buenos Aires', 
    1168178000, 
    'Dr. Martín Sánchez', 
    'Hospital'
);

-- Insert para fila 23
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Italiano de Buenos Aires', 
    'INFO@HIBA.ORG.AR', 
    'CONTACTO@HIBA.ORG.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Eduardo Fernández', 
    'Dr. Ana López', 
    NULL, 
    NULL, 
    NULL, 
    1145309000, 
    1145309111, 
    NULL, 
    NULL, 
    NULL, 
    'Juan D. Perón 4190', 
    'Buenos Aires', 
    'Buenos Aires', 
    1145309000, 
    'Dr. Eduardo Fernández', 
    'Hospital'
);

-- Insert para fila 24
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital de Clínicas José de San Martín', 
    'INFO@HOSPITALDECLINICAS.UBA.AR', 
    'CONTACTO@HOSPITALDECLINICAS.UBA.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Alejandro López', 
    'Dr. María Rodríguez', 
    NULL, 
    NULL, 
    NULL, 
    1145928000, 
    1145928111, 
    NULL, 
    NULL, 
    NULL, 
    'Av. Córdoba 2351', 
    'Buenos Aires', 
    'Buenos Aires', 
    1145928000, 
    'Dr. Alejandro López', 
    'Hospital'
);

-- Insert para fila 25
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital de Niños Ricardo Gutiérrez', 
    'INFO@HNRG.ORG.AR', 
    'CONTACTO@HNRG.ORG.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Carlos Sánchez', 
    'Dr. Laura Martínez', 
    NULL, 
    NULL, 
    NULL, 
    1143017000, 
    1143017111, 
    NULL, 
    NULL, 
    NULL, 
    'Gallo 1330', 
    'Buenos Aires', 
    'Buenos Aires', 
    1143017000, 
    'Dr. Carlos Sánchez', 
    'Hospital'
);

-- Insert para fila 26
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Posadas', 
    'INFO@HOSPITALPOSADAS.GOB.AR', 
    'CONTACTO@HOSPITALPOSADAS.GOB.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Juan Pérez', 
    'Dr. María Rodríguez', 
    NULL, 
    NULL, 
    NULL, 
    1146620200, 
    1146620300, 
    NULL, 
    NULL, 
    NULL, 
    'Av. Presidente Illia s/n', 
    'El Palomar', 
    'Buenos Aires', 
    1146620200, 
    'Dr. Juan Pérez', 
    'Hospital'
);

-- Insert para fila 27
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Ramos Mejía', 
    'INFO@HOSPITALRAMOSMEJIA.BA.GOV.AR', 
    'CONTACTO@HOSPITALRAMOSMEJIA.BA.GOV.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Martín Fernández', 
    'Dr. Laura Martínez', 
    NULL, 
    NULL, 
    NULL, 
    1144339500, 
    1144339600, 
    NULL, 
    NULL, 
    NULL, 
    'Urquiza 609', 
    'Buenos Aires', 
    'Buenos Aires', 
    1144339500, 
    'Dr. Martín Fernández', 
    'Hospital'
);

-- Insert para fila 28
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Italiano de La Plata', 
    'INFO@HOSPITALITALIANOLP.ORG.AR', 
    'CONTACTO@HOSPITALITALIANOLP.ORG.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Marcos Pérez', 
    'Dr. Sofía Gómez', 
    NULL, 
    NULL, 
    NULL, 
    2216105000, 
    2216105111, 
    NULL, 
    NULL, 
    NULL, 
    'Calle 51 Nº 320', 
    'La Plata', 
    'Buenos Aires', 
    2216105000, 
    'Dr. Marcos Pérez', 
    'Hospital'
);

-- Insert para fila 29
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital de Pediatría Prof. Dr. Juan P. Garrahan', 
    'INFO@HOSPITALGARRAHAN.GOV.AR', 
    'CONTACTO@HOSPITALGARRAHAN.GOV.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Sebastián Pérez', 
    'Dr. Ana López', 
    NULL, 
    NULL, 
    NULL, 
    1143005400, 
    1143005411, 
    NULL, 
    NULL, 
    NULL, 
    'Combate de los Pozos 1881', 
    'Buenos Aires', 
    'Buenos Aires', 
    1143005400, 
    'Dr. Sebastián Pérez', 
    'Hospital'
);

-- Insert para fila 30
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Privado de Rosario', 
    'INFO@HOSPITALPRIVADOROSARIO.COM.AR', 
    'CONTACTO@HOSPITALPRIVADOROSARIO.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Juan Martínez', 
    'Dr. María Rodríguez', 
    NULL, 
    NULL, 
    NULL, 
    3414486700, 
    3414486711, 
    NULL, 
    NULL, 
    NULL, 
    'Urquiza 3101', 
    'Rosario', 
    'Santa Fe', 
    3414486700, 
    'Dr. Juan Martínez', 
    'Hospital'
);

-- Insert para fila 31
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Italiano de Mendoza', 
    'INFO@HOSPITALITALIANOMZA.ORG.AR', 
    'CONTACTO@HOSPITALITALIANOMZA.ORG.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Marcos Gutiérrez', 
    'Dra. Laura Pérez', 
    NULL, 
    NULL, 
    NULL, 
    2614478900, 
    2614478911, 
    NULL, 
    NULL, 
    NULL, 
    'Patricias Mendocinas 1550', 
    'Mendoza', 
    'Mendoza', 
    2614478900, 
    'Dr. Marcos Gutiérrez', 
    'Hospital'
);

-- Insert para fila 32
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Hospital Italiano de Bahía Blanca', 
    'INFO@HOSPITALITALIANOBB.ORG.AR', 
    'CONTACTO@HOSPITALITALIANOBB.ORG.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Juan Sánchez', 
    'Dra. Ana Martínez', 
    NULL, 
    NULL, 
    NULL, 
    2914567800, 
    2914567811, 
    NULL, 
    NULL, 
    NULL, 
    'Donado 401', 
    'Bahía Blanca', 
    'Buenos Aires', 
    2914567800, 
    'Dr. Juan Sánchez', 
    'Hospital'
);

-- Insert para fila 33
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio Allende', 
    'INFO@SANATORIOALLENDE.COM.AR', 
    'CONTACTO@SANATORIOALLENDE.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. José Martínez', 
    'Dra. María Sánchez', 
    NULL, 
    NULL, 
    NULL, 
    3514009000, 
    3514009111, 
    NULL, 
    NULL, 
    NULL, 
    'Humberto Primo 1200', 
    'Córdoba', 
    'Córdoba', 
    3514009000, 
    'Dr. José Martínez', 
    'Hospital'
);

-- Insert para fila 34
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio Güemes', 
    'INFO@SANATORIOGUEMES.COM.AR', 
    'CONTACTO@SANATORIOGUEMES.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Carlos Martínez', 
    'Dr. Pablo Gómez', 
    NULL, 
    NULL, 
    NULL, 
    3814505000, 
    3814505123, 
    NULL, 
    NULL, 
    NULL, 
    'Av. Entre Ríos 450', 
    'San Miguel de Tucumán', 
    'Tucumán', 
    3814505000, 
    'Dr. Carlos Martínez', 
    'Hospital'
);

-- Insert para fila 35
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Clínica Santa Isabel', 
    'INFO@CLINICASANTAISABEL.COM.AR', 
    'CONTACTO@CLINICASANTAISABEL.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Juan Pérez', 
    'Dra. Laura Sánchez', 
    NULL, 
    NULL, 
    NULL, 
    3874628700, 
    3874628711, 
    NULL, 
    NULL, 
    NULL, 
    'San Martín 1350', 
    'Salta', 
    'Salta', 
    3874628700, 
    'Dr. Juan Pérez', 
    'Hospital'
);

-- Insert para fila 36
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio Otamendi y Miroli', 
    'INFO@OTAMENDI.COM.AR', 
    'CONTACTO@OTAMENDI.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Federico López', 
    'Dra. Ana Martínez', 
    NULL, 
    NULL, 
    NULL, 
    1143084000, 
    1143084111, 
    NULL, 
    NULL, 
    NULL, 
    'Azcuénaga 870', 
    'Buenos Aires', 
    'Buenos Aires', 
    1143084000, 
    'Dr. Federico López', 
    'Hospital'
);

-- Insert para fila 37
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio Güemes', 
    'INFO@SANATORIOGUEMES.COM.AR', 
    'CONTACTO@SANATORIOGUEMES.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Carlos Martínez', 
    'Dr. Pablo Gómez', 
    NULL, 
    NULL, 
    NULL, 
    3814505000, 
    3814505123, 
    NULL, 
    NULL, 
    NULL, 
    'Av. Entre Ríos 450', 
    'San Miguel de Tucumán', 
    'Tucumán', 
    3814505000, 
    'Dr. Carlos Martínez', 
    'Hospital'
);

-- Insert para fila 38
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio Mater Dei', 
    'INFO@SANATORIOMATERDEI.COM.AR', 
    'CONTACTO@SANATORIOMATERDEI.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Juan Martínez', 
    'Dra. María Rodríguez', 
    NULL, 
    NULL, 
    NULL, 
    1143698700, 
    1143698711, 
    NULL, 
    NULL, 
    NULL, 
    'Hidalgo 2390', 
    'Buenos Aires', 
    'Buenos Aires', 
    1143698700, 
    'Dr. Juan Martínez', 
    'Hospital'
);

-- Insert para fila 39
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio La Trinidad Palermo', 
    'INFO@SANATORIOLATRINIDAD.COM.AR', 
    'CONTACTO@SANATORIOLATRINIDAD.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Federico Pérez', 
    'Dra. Laura Gómez', 
    NULL, 
    NULL, 
    NULL, 
    1148456000, 
    1148456111, 
    NULL, 
    NULL, 
    NULL, 
    'Guardia Vieja 4435', 
    'Buenos Aires', 
    'Buenos Aires', 
    1148456000, 
    'Dr. Federico Pérez', 
    'Hospital'
);

-- Insert para fila 40
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'Sanatorio Güemes', 
    'INFO@SANATORIOGUEMES.COM.AR', 
    'CONTACTO@SANATORIOGUEMES.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'Dr. Carlos Martínez', 
    'Dr. Pablo Gómez', 
    NULL, 
    NULL, 
    NULL, 
    3814505000, 
    3814505123, 
    NULL, 
    NULL, 
    NULL, 
    'Av. Entre Ríos 450', 
    'San Miguel de Tucumán', 
    'Tucumán', 
    3814505000, 
    'Dr. Carlos Martínez', 
    'Hospital'
);

/*-------------------------------------------*/
-- Insert para Hospital Pico Truncado
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL DISTRITAL PICO TRUNCADO', 
    'LEOPEREZ833@HOTMAIL.COM', 
    'OPORTUNIDAD@MPT.COM.AR', 
    'PABLINCHO2002@YAHOO.COM', 
    'HPT@SANTACRUZ.GOV.AR', 
    NULL, 
    'DR PABLO CAPRA', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    2974992192, 
    2974990494, 
    2974990119, 
    NULL, 
    NULL, 
    'VELEZ SARSFIELD 305 (CASILLA DE CORREO NRO 8)', 
    'PICO TRUNCADO', 
    'SANTA CRUZ', 
    2974992192, 
    'DR PABLO CAPRA', 
    NULL
);

-- Insert para Hospital Piedra Buena
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL SECCIONAL DR ARMANDO ZAMUDIO', 
    'LABPIEDRABUENA@YAHOO.COM.AR', 
    'MARSH052004@YAHOO.COM.AR', 
    'DRAMARIAFERNANDA2003@HOTMAIL.COM', 
    'BRENDA_YP@HOTMAIL.COM', 
    NULL, 
    'BIOQ MARCELO CASTRO', 
    'MARIA FERNANDA ROLON', 
    NULL, 
    NULL, 
    NULL, 
    2962497125, 
    29661547125, 
    NULL, 
    NULL, 
    NULL, 
    'SAENZ PEÑA S/N', 
    'COMANDANTE LUIS PIEDRA BUENA', 
    'SANTA CRUZ', 
    2962497125, 
    'BIOQ MARCELO CASTRO', 
    'LABORATORIO'
);

-- Insert para Hospital Pilcaniyeu
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL AREA PROGRAMA PILCANIYEU', 
    'JENNYURDI@HOTMAIL.COM', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'JENNY URDIROS', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'LOS CHOIQUES Y AIMOE PAINE', 
    'PILCANIYEU', 
    'RIO NEGRO', 
    NULL, 
    'JENNY URDIROS', 
    NULL
);

-- Insert para Hospital Ponte
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'LABORATORIO DE ANALISIS CLINICOS', 
    'LABPSC@ARNET.COM.AR', 
    'LAB47@NETIUM.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'DR. NORBERTO PONTE', 
    'DR. GUILLERMO CODINO', 
    NULL, 
    NULL, 
    NULL, 
    3435421309, 
    3435421309, 
    NULL, 
    NULL, 
    NULL, 
    'BV ESPAÑA 961', 
    'NOGOYA', 
    'ENTRE RIOS', 
    3435421309, 
    'DR. NORBERTO PONTE', 
    'LABORATORIO DE ANALISIS CLINICOS'
);

-- Insert para Hospital Posadas
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL PEDIATRICO DR F. PEDRO FUCHS', 
    'DRCARLOSB@HOTMAIL.COM', 
    'FLORENCIAALLEN@HOTMAIL.COM', 
    NULL, 
    NULL, 
    NULL, 
    'DR CARLOS BARRIOS', 
    'FLORENCIA ALLEN', 
    NULL, 
    NULL, 
    NULL, 
    '3764448017', 
    NULL, 
    NULL, 
    NULL, 
    'AV RIVADAVIA 2359', 
    'POSADAS', 
    'MISIONES', 
    '3764448017', 
    'DR CARLOS BARRIOS', 
    'PEDIATRIA'
);

-- Insert para Hospital Puan
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL DE PUAN', 
    'HOSPITALPUAN@GMAIL.COM', 
    'JULIOCESARL@YAHOO.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'DRA. CINTIA RODRIGUEZ', 
    'DR. JULIO LUNA', 
    NULL, 
    NULL, 
    NULL, 
    '2923510300', 
    '2923511155', 
    NULL, 
    NULL, 
    NULL, 
    'SAN MARTIN 951', 
    'PUAN', 
    'BUENOS AIRES', 
    '2923510300', 
    'DRA. CINTIA RODRIGUEZ', 
    NULL
);

-- Insert para Hospital Quilmes
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL ISIDORO IRIARTE', 
    'HOSPITALIRIARTE@GMAIL.COM', 
    'SERVICIOSMUNICIPIO@HOTMAIL.COM', 
    NULL, 
    NULL, 
    NULL, 
    'DRA. MARIA FERNANDA PEREZ', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    '42242570', 
    NULL, 
    NULL, 
    NULL, 
    'AMBROSINI Y DRAGO 530', 
    'QUILMES', 
    'BUENOS AIRES', 
    '42242570', 
    'DRA. MARIA FERNANDA PEREZ', 
    NULL
);

-- Insert para Hospital Reconquista
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL RECONQUISTA', 
    'INFOHOSPITAL@HOSPITALRECONQUISTA.COM.AR', 
    'HOSPITALRRPP@HOSPITALRECONQUISTA.COM.AR', 
    'DRCARLOSORTIZ@HOSPITALRECONQUISTA.COM.AR', 
    NULL, 
    NULL, 
    'DR CARLOS ORTIZ', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    '3482416791', 
    NULL, 
    NULL, 
    NULL, 
    'AV. DANTE A. MONTAÑEZ 500', 
    'RECONQUISTA', 
    'SANTA FE', 
    '3482416791', 
    'DR CARLOS ORTIZ', 
    NULL
);

-- Insert para Hospital Resistencia
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL PEDIÁTRICO P. ELIZALDE', 
    'DRALEILA@HOTMAIL.COM', 
    'CECILIAROCA2008@GMAIL.COM', 
    NULL, 
    NULL, 
    NULL, 
    'DRA. LEILA PEREZ', 
    'DRA. CECILIA ROCA', 
    NULL, 
    NULL, 
    NULL, 
    '3722427100', 
    NULL, 
    NULL, 
    NULL, 
    'AV. MADARIAGA 637', 
    'RESISTENCIA', 
    'CHACO', 
    '3722427100', 
    'DRA. LEILA PEREZ', 
    NULL
);

-- Insert para Hospital Rio Cuarto
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL SAN ANTONIO DE PADUA', 
    'HOSPITALSANANTONIODEPADUA@GMAIL.COM', 
    'DRCARLOSALBERTO@HOSPITAL.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'DR. CARLOS ALBERTO', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    '3584621456', 
    NULL, 
    NULL, 
    NULL, 
    'CHILE Y LAS HERAS 400', 
    'RIO CUARTO', 
    'CORDOBA', 
    '3584621456', 
    'DR. CARLOS ALBERTO', 
    NULL
);

-- Insert para Hospital Rio Gallegos
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL REGIONAL RIO GALLEGOS', 
    'CONTACTO@HOSPITALRIOGALLEGOS.COM.AR', 
    'RRPPHOSPITALRIOGALLEGOS@HOTMAIL.COM', 
    NULL, 
    NULL, 
    NULL, 
    'DR. JUAN PEREZ', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    '2966489710', 
    NULL, 
    NULL, 
    NULL, 
    'DR. LUCAS MIRANDA 750', 
    'RIO GALLEGOS', 
    'SANTA CRUZ', 
    '2966489710', 
    'DR. JUAN PEREZ', 
    NULL
);

-- Insert para Hospital Rio Grande
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL REGIONAL RIO GRANDE', 
    'DRJUANPEREZ@HOTMAIL.COM', 
    'MARCELOALVAREZ@HOSPITALRIOGRANDE.COM.AR', 
    NULL, 
    NULL, 
    NULL, 
    'DR. JUAN PEREZ', 
    'DR. MARCELO ALVAREZ', 
    NULL, 
    NULL, 
    NULL, 
    '2964423679', 
    NULL, 
    NULL, 
    NULL, 
    'BELGRANO 350', 
    'RIO GRANDE', 
    'TIERRA DEL FUEGO', 
    '2964423679', 
    'DR. JUAN PEREZ', 
    NULL
);


-- Continuar con los inserts para los otros registros según el mismo formato.
-- Insert para Hospital Rivadavia
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL PEDRO J. SARMIENTO', 
    'CONTACTO@HOSPITALRIVADAVIA.COM.AR', 
    'DRPABLOLOPEZ@HOSPITALRIVADAVIA.COM.AR', 
    '', 
    '', 
    '', 
    'DR. PABLO LOPEZ', 
    '', 
    '', 
    '', 
    '', 
    '2634358976', 
    '', 
    '', 
    '', 
    'RIVADAVIA 857', 
    'RIVADAVIA', 
    'MENDOZA', 
    '2634358976', 
    'DR. PABLO LOPEZ', 
    ''
);

-- Insert para Hospital Rosario
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL CENTENARIO', 
    'HOSPITALCENTENARIO@HOTMAIL.COM', 
    'DRAANAORTIZ@HOSPITALCENTENARIO.COM.AR', 
    '', 
    '', 
    '', 
    'DRA. ANA ORTIZ', 
    '', 
    '', 
    '', 
    '', 
    '3414512876', 
    '', 
    '', 
    '', 
    'AV. PATRIA 545', 
    'ROSARIO', 
    'SANTA FE', 
    '3414512876', 
    'DRA. ANA ORTIZ', 
    ''
);

-- Insert para Hospital Salta
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL PÚBLICO DE GESTIÓN DESCONCENTRADA DR. ARTURO OÑATIVIA', 
    'CONTACTO@HOSPITALSALTA.COM.AR', 
    'DRJUANMARTINEZ@HOSPITALSALTA.COM.AR', 
    '', 
    '', 
    '', 
    'DR. JUAN MARTINEZ', 
    '', 
    '', 
    '', 
    '', 
    '3874512876', 
    '', 
    '', 
    '', 
    'SAN MARTIN 1045', 
    'SALTA', 
    'SALTA', 
    '3874512876', 
    'DR. JUAN MARTINEZ', 
    ''
);

-- Insert para Hospital San Fernando del Valle de Catamarca
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL SAN JUAN BAUTISTA', 
    'HOSPITALSANJUANBAUTISTA@CATAMARCA.COM.AR', 
    'DRAANAALVAREZ@CATAMARCA.COM.AR', 
    '', 
    '', 
    '', 
    'DRA. ANA ALVAREZ', 
    '', 
    '', 
    '', 
    '', 
    '3834532876', 
    '', 
    '', 
    '', 
    'SAN MARTIN 1567', 
    'SAN FERNANDO DEL VALLE DE CATAMARCA', 
    'CATAMARCA', 
    '3834532876', 
    'DRA. ANA ALVAREZ', 
    ''
);

-- Insert para Hospital San Juan
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL RAWSON', 
    'HOSPITALRAWSON@HOTMAIL.COM', 
    'DRCARLOSRUIZ@HOSPITALRAWSON.COM.AR', 
    '', 
    '', 
    '', 
    'DR. CARLOS RUIZ', 
    '', 
    '', 
    '', 
    '', 
    '2644525876', 
    '', 
    '', 
    '', 
    'AV. RAWSON 1095', 
    'SAN JUAN', 
    'SAN JUAN', 
    '2644525876', 
    'DR. CARLOS RUIZ', 
    ''
);

-- Insert para Hospital San Luis
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL SAN LUIS', 
    'HOSPITALSANLUIS@SANLUIS.COM.AR', 
    'DRAANAMARTINEZ@SANLUIS.COM.AR', 
    '', 
    '', 
    '', 
    'DRA. ANA MARTINEZ', 
    '', 
    '', 
    '', 
    '', 
    '2664529876', 
    '', 
    '', 
    '', 
    'RIVADAVIA 1040', 
    'SAN LUIS', 
    'SAN LUIS', 
    '2664529876', 
    'DRA. ANA MARTINEZ', 
    ''
);

-- Insert para Hospital San Rafael
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL TEODORO SCHESTAKOW', 
    'HOSPITALSANRAFAEL@GMAIL.COM', 
    'DRJORGEMARTINEZ@HOSPITALSANRAFAEL.COM.AR', 
    '', 
    '', 
    '', 
    'DR. JORGE MARTINEZ', 
    '', 
    '', 
    '', 
    '', 
    '2604523678', 
    '', 
    '', 
    '', 
    'MITRE 852', 
    'SAN RAFAEL', 
    'MENDOZA', 
    '2604523678', 
    'DR. JORGE MARTINEZ', 
    ''
);

-- Insert para Hospital Santa Fe
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL ITURRASPE', 
    'HOSPITALITURRASPE@SANTAFE.COM.AR', 
    'DRAJULIAMARTINEZ@HOSPITALITURRASPE.COM.AR', 
    '', 
    '', 
    '', 
    'DRA. JULIA MARTINEZ', 
    '', 
    '', 
    '', 
    '', 
    '3424569876', 
    '', 
    '', 
    '', 
    'AV. ALEM 355', 
    'SANTA FE', 
    'SANTA FE', 
    '3424569876', 
    'DRA. JULIA MARTINEZ', 
    ''
);

-- Insert para Hospital Santiago del Estero
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL REGIONAL DR. LUIS MARTÍNEZ', 
    'HOSPITALSANTIAGODELESTERO@GMAIL.COM', 
    'DRJUANMARTINEZ@HOSPITALSANTIAGODELESTERO.COM.AR', 
    '', 
    '', 
    '', 
    'DR. JUAN MARTINEZ', 
    '', 
    '', 
    '', 
    '', 
    '3854529876', 
    '', 
    '', 
    '', 
    'AV. BELGRANO 750', 
    'SANTIAGO DEL ESTERO', 
    'SANTIAGO DEL ESTERO', 
    '3854529876', 
    'DR. JUAN MARTINEZ', 
    ''
);

-- Insert para Hospital Santo Tomé
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL ZONAL DR. RENÉ FAVOLORO', 
    'CONTACTO@HOSPITALSANTOTOME.COM.AR', 
    'DRAANAALVAREZ@HOSPITALSANTOTOME.COM.AR', 
    '', 
    '', 
    '', 
    'DRA. ANA ALVAREZ', 
    '', 
    '', 
    '', 
    '', 
    '3754569876', 
    '', 
    '', 
    '', 
    'SAN MARTIN 880', 
    'SANTO TOMÉ', 
    'CORRIENTES', 
    '3754569876', 
    'DRA. ANA ALVAREZ', 
    ''
);

-- Insert para Hospital Tucumán
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL PADILLA', 
    'HOSPITALPADILLA@TUCUMAN.COM.AR', 
    'DRJUANPEREZ@HOSPITALPADILLA.COM.AR', 
    '', 
    '', 
    '', 
    'DR. JUAN PEREZ', 
    '', 
    '', 
    '', 
    '', 
    '3814512876', 
    '', 
    '', 
    '', 
    'AV. SARMIENTO 325', 
    'SAN MIGUEL DE TUCUMÁN', 
    'TUCUMAN', 
    '3814512876', 
    'DR. JUAN PEREZ', 
    ''
);

-- Insert para Hospital Ushuaia
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL REGIONAL USHUAIA', 
    'CONTACTO@HOSPITALUSHUAIA.COM.AR', 
    'DRJORGELOPEZ@HOSPITALUSHUAIA.COM.AR', 
    '', 
    '', 
    '', 
    'DR. JORGE LOPEZ', 
    '', 
    '', 
    '', 
    '', 
    '2904529876', 
    '', 
    '', 
    '', 
    'AV. SAN MARTIN 345', 
    'USHUAIA', 
    'TIERRA DEL FUEGO', 
    '2904529876', 
    'DR. JORGE LOPEZ', 
    ''
);

-- Insert para Hospital Viedma
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL ZATTI', 
    'HOSPITALZATTI@GMAIL.COM', 
    'DRAANAMARTINEZ@HOSPITALZATTI.COM.AR', 
    '', 
    '', 
    '', 
    'DRA. ANA MARTINEZ', 
    '', 
    '', 
    '', 
    '', 
    '2924569876', 
    '', 
    '', 
    '', 
    'SAN MARTIN 1080', 
    'VIEDMA', 
    'RIO NEGRO', 
    '2924569876', 
    'DRA. ANA MARTINEZ', 
    ''
);

-- Insert para Hospital Villa Maria
INSERT INTO Hospital (
    NombreHospital, 
    Email1, 
    Email2, 
    Email3, 
    Email4, 
    Email5, 
    Referente1, 
    Referente2, 
    Referente3, 
    Referente4, 
    Referente5, 
    Tel1, 
    Tel2, 
    Tel3, 
    Tel4, 
    Tel5, 
    Direccion, 
    Localidad, 
    Provincia, 
    Telefono, 
    Responsable, 
    Servicio
) VALUES (
    'HOSPITAL REGIONAL VICENTE AGÜERO', 
    'CONTACTO@HOSPITALVILLAMARIA.COM.AR', 
    'DRJUANPEREZ@HOSPITALVILLAMARIA.COM.AR', 
    '', 
    '', 
    '', 
    'DR. JUAN PEREZ', 
    '', 
    '', 
    '', 
    '', 
    '3534512876', 
    '', 
    '', 
    '', 
    'AV. CARRANZA 780', 
    'VILLA MARIA', 
    'CORDOBA', 
    '3534512876', 
    'DR. JUAN PEREZ', 
    ''
);

